# Generated by Django 4.2.1 on 2023-06-09 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='last_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.CharField(default='blog space', max_length=1000000),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
