# Generated by Django 4.2.1 on 2023-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
