# Generated by Django 4.2.1 on 2023-06-29 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_write_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 6, 29, 1, 59, 20, 901067, tzinfo=datetime.timezone.utc), upload_to='../static'),
            preserve_default=False,
        ),
    ]
