# Generated by Django 4.2.1 on 2023-07-07 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='imageHomepage',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='main_body',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imagePrimary',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imageSecondary',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='mainTopic_head',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='subtopic_body',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtopic_head',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='topicIntro_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='topicIntro_head',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
