# Generated by Django 4.2.1 on 2024-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_image_blog_imagehomepage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='main_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='imageHomepage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imagePrimary',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageSecondary',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mainTopic_head',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtopic_body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtopic_head',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='topicIntro_body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='topicIntro_head',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
